### ISSUE TITLE
Variables Import

### ISSUE THREAD

**Issue by lmantesbtm** [tiagohm/restler#54]
Hi,

This will be like a suggestion if it can be done.

Similar to insomnia which you can put the Environment Variables, is there anything like this
in Restler?

As my imported JSON file came from Insomnia, I have put the HOST and the TOKEN (authorization token header) as an Environment Variable so I don't have to copy these values to every single API that I made. Without this, the imported JSON file is almost no use.
ex: http://{{ host }}/api/something - host came from the ENV of insomnia.

Thank you again for fixing the issue #52 , I can import the JSON file now.

**Comment by tiagohm** [comment]
Hi,

Thanks for the suggestion. This is in the plans for future versions (#28) as well as switch between environments and workspaces (#30).

**Comment by lmantesbtm** [comment]
Hi, 

Thanks for the update. Looking forward to your next iterations.
