### ISSUE TITLE
Mention Android in repository description

### ISSUE THREAD

**Issue by tarasyyyk** [tiagohm/restler#85]
There are many projects named "Restler" on GitHub. But not all for Android. It would be good to mention OS platform this app is created for. So, anybody hwo searches "android test api" can find this project. For example: "_Restler is a beautiful and powerful **Android app** for testing REST API anywhere and anytime. http://restler.tiagohm.xyz_"

**Comment by tiagohm** [comment]
Thanks for feedback. I edited the description.
